endpoints:
    - api-interface: jsonrpc
      chain-id: ETH1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: GTH1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: FTM250
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: CELO
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: ALFAJORES
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: ARB1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: STRK
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: APT1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: POLYGON1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: OPTM
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: BASET
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: OSMOSIS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: OSMOSIS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: OSMOSIS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: OSMOSIST
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: OSMOSIST
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: OSMOSIST
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: COSMOSHUB
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: COSMOSHUB
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: COSMOSHUB
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: JUN1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: JUN1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: JUN1
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: CANTO
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: CANTO
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: CANTO
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: CANTO
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: rest
      chain-id: AXELAR
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: tendermintrpc
      chain-id: AXELAR
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: grpc
      chain-id: AXELAR
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: BSC
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: SOLANA
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
    - api-interface: jsonrpc
      chain-id: SUIT
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: <enter-here>
