endpoints:
    - name: provider-2222-tendermintrpc
      api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: wss://lava-archive.lavanet.xyz/websocket
        - url: https://lava-archive.lavanet.xyz/rpc/
        - url: https://lava-archive.lavanet.xyz/rpc/
          addons:
            - archive
        - url: wss://lava-archive.lavanet.xyz/websocket
          addons:
            - archive
    - name: provider-2222-rest
      api-interface: rest
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls: 
        - url: https://lava-archive.lavanet.xyz/rest/
        - url: https://lava-archive.lavanet.xyz/rest/
          addons:
            - archive
    - name: provider-2222-grpc
      api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: grpc-lava-archive.lavanet.xyz:443
        - url: grpc-lava-archive.lavanet.xyz:443
          addons:
            - archive
