endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: ws://127.0.0.1:26657/websocket
        - url: http://127.0.0.1:26657
        - url: http://127.0.0.1:26657
          addons:
            - archive
    - api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: 127.0.0.1:9090
        - url: 127.0.0.1:9090
          addons:
            - archive
    - api-interface: rest
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls: 
        - url: http://127.0.0.1:1317
        - url: http://127.0.0.1:1317
          addons:
            - archive
