endpoints:
    - name: provider-2222-tendermintrpc
      api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: wss://lav1.tendermintrpc.lava.build/websocket
        - url: https://lav1.tendermintrpc.lava.build:443
        - url: https://lav1.tendermintrpc.lava.build:443
          addons:
            - archive
        - url: wss://lav1.tendermintrpc.lava.build/websocket
          addons:
            - archive
    - name: provider-2222-rest
      api-interface: rest
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls: 
        - url: https://lav1.rest.lava.build:443
        - url: https://lav1.rest.lava.build:443
          addons:
            - archive
    - name: provider-2222-grpc
      api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2222"
      node-urls:
        - url: lav1.grpc.lava.build:443
        - url: lav1.grpc.lava.build:443
          addons:
            - archive
