endpoints:
    - chain-id: ETH1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3333
    - chain-id: GTH1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3334
    - chain-id: FTM250
      api-interface: jsonrpc
      network-address: 127.0.0.1:3335
    - chain-id: CELO
      api-interface: jsonrpc
      network-address: 127.0.0.1:3346
    - chain-id: ALFAJORES
      api-interface: jsonrpc
      network-address: 127.0.0.1:3347
    - chain-id: ARB1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3348      
    - chain-id: STRK
      api-interface: jsonrpc
      network-address: 127.0.0.1:3349
    - chain-id: APT1
      api-interface: rest
      network-address: 127.0.0.1:3350
    - chain-id: POLYGON1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3351
    - chain-id: OPTM
      api-interface: jsonrpc
      network-address: 127.0.0.1:3352
    - chain-id: BASET
      api-interface: jsonrpc
      network-address: 127.0.0.1:3353
    - chain-id: OSMOSIS
      api-interface: rest
      network-address: 127.0.0.1:3354
    - chain-id: OSMOSIS
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3355
    - chain-id: OSMOSIS
      api-interface: grpc
      network-address: 127.0.0.1:3356
    - chain-id: OSMOSIST
      api-interface: rest
      network-address: 127.0.0.1:3357
    - chain-id: OSMOSIST
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3358
    - chain-id: OSMOSIST
      api-interface: grpc
      network-address: 127.0.0.1:3359
    - chain-id: LAV1
      api-interface: rest
      network-address: 127.0.0.1:3360
    - chain-id: LAV1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3361
    - chain-id: LAV1
      api-interface: grpc
      network-address: 127.0.0.1:3362
    - chain-id: COSMOSHUB
      api-interface: rest
      network-address: 127.0.0.1:3363
    - chain-id: COSMOSHUB
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3364
    - chain-id: COSMOSHUB
      api-interface: grpc
      network-address: 127.0.0.1:3365
    - chain-id: JUN1
      api-interface: rest
      network-address: 127.0.0.1:3366
    - chain-id: JUN1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3367
    - chain-id: JUN1
      api-interface: grpc
      network-address: 127.0.0.1:3368
    - chain-id: EVMOS
      api-interface: jsonrpc
      network-address: 127.0.0.1:3369
    - chain-id: EVMOS
      api-interface: rest
      network-address: 127.0.0.1:3370
    - chain-id: EVMOS
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3371
    - chain-id: EVMOS
      api-interface: grpc
      network-address: 127.0.0.1:3372
    - chain-id: CANTO
      api-interface: jsonrpc
      network-address: 127.0.0.1:3373
    - chain-id: CANTO
      api-interface: rest
      network-address: 127.0.0.1:3374
    - chain-id: CANTO
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3375
    - chain-id: CANTO
      api-interface: grpc
      network-address: 127.0.0.1:3376
    - chain-id: AXELAR
      api-interface: rest
      network-address: 127.0.0.1:3377
    - chain-id: AXELAR
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3378
    - chain-id: AXELAR
      api-interface: grpc
      network-address: 127.0.0.1:3379
    - chain-id: BSC
      api-interface: jsonrpc
      network-address: 127.0.0.1:3380
    - chain-id: SOLANA
      api-interface: jsonrpc
      network-address: 127.0.0.1:3381
    - chain-id: SUIT
      api-interface: jsonrpc
      network-address: 127.0.0.1:3382
    - chain-id: AVAX
      api-interface: jsonrpc
      network-address: 127.0.0.1:3383
    - chain-id: FVM
      api-interface: jsonrpc
      network-address: 127.0.0.1:3384
    - chain-id: NEAR
      api-interface: jsonrpc
      network-address: 127.0.0.1:3385
    - chain-id: AGR
      api-interface: rest
      network-address: 127.0.0.1:3386
    - chain-id: AGR
      api-interface: grpc
      network-address: 127.0.0.1:3387
    - chain-id: AGR
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3388
    - chain-id: AGRT
      api-interface: rest
      network-address: 127.0.0.1:3389
    - chain-id: AGRT
      api-interface: grpc
      network-address: 127.0.0.1:3390
    - chain-id: AGRT
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3391
    - chain-id: KOIIT
      api-interface: jsonrpc
      network-address: 127.0.0.1:3392
    - chain-id: AVAXT
      api-interface: jsonrpc
      network-address: 127.0.0.1:3393
metrics-listen-address: ":7779"
# referer-be-address: "http://127.0.0.1:6500"
# reports-be-address: "http://127.0.0.1:6501"