endpoints:
    - chain-id: ETH1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3360
static-providers:
  - name: primary-2220-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2220
        addons:
          - archive
  - name: primary-2221-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2221
        addons:
          - debug
          - archive
  - name: primary-2222-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2222
        addons:
          - debug
          - archive

backup-providers:
  - name: backup-2220-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2220
        addons:
          - archive
  - name: backup-2221-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2221
        addons:
          - debug
          - archive
  - name: backup-2222-jsonrpc
    api-interface: jsonrpc
    chain-id: ETH1
    node-urls:
      - url: 127.0.0.1:2222
        addons:
          - debug
          - archive