endpoints:
    - chain-id: LAV1
      api-interface: rest
      network-address: 127.0.0.1:3360
    - chain-id: LAV1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3361
    - chain-id: LAV1
      api-interface: grpc
      network-address: 127.0.0.1:3362
static-providers:
  - name: primary-2220-tendermintrpc
    api-interface: tendermintrpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
        addons:
          - archive
          - debug
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]
  - name: primary-2220-grpc
    api-interface: grpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]
  - name: primary-2220-rest
    api-interface: rest
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]
  - name: primary-2221-tendermintrpc
    api-interface: tendermintrpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]
  - name: primary-2221-grpc
    api-interface: grpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]
  - name: primary-2221-rest
    api-interface: rest
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221
        skip-verifications: [chain-id,minimum-gas-price, tx-indexing, node-info]

backup-providers:
  - name: backup-2220-tendermintrpc
    api-interface: tendermintrpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
  - name: backup-2220-grpc
    api-interface: grpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
  - name: backup-2220-rest
    api-interface: rest
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
  - name: backup-2221-tendermintrpc
    api-interface: tendermintrpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221
  - name: backup-2221-grpc
    api-interface: grpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221
  - name: backup-2221-rest
    api-interface: rest
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2221