---
{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "provider.fullname"  . }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
    lavanet.xyz/node_moniker:  {{ include "provider.moniker"  . }}    
    lavanet.xyz/node_type: "provider"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .Values.ingress.tls | nindent 4) . }}
  {{- end }}
  {{-  if .Values.ingress.rules }}
  rules:
    {{- tpl (toYaml .Values.ingress.rules | nindent 4) . }}
  {{- end }}
{{- end }}