name: 'Network upgrade trigger'

on:
  push:
    tags

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Trigger Network Upgrade
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.repos.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: "network-upgrades",
            workflow_id: "validators.yml",
            ref: github.ref
          })
